// courses.js
export const FETCH_COURSE = 'FETCH_COURSE';
export const FETCH_COURSES = 'FETCH_COURSES';
export const TOGGLE_ADD_COURSE_MODAL = 'TOGGLE_ADD_COURSE_MODAL';
export const ADD_COURSE = 'ADD_COURSE';
export const SET_TITLE = 'SET_TITLE';
export const SET_CODE = 'SET_CODE';
export const SET_DESCRIPTION = 'SET_DESCRIPTION';
export const SET_POINTS = 'SET_POINTS';
export const SET_LEVEL = 'SET_LEVEL';
export const EDIT_COURSE_TITLE = 'EDIT_COURSE_TITLE';
export const EDIT_COURSE_CODE = 'EDIT_COURSE_CODE';
export const EDIT_COURSE_DESCRIPTION = 'EDIT_COURSE_DESCRIPTION';
export const EDIT_COURSE_POINTS = 'EDIT_COURSE_POINTS';
export const EDIT_COURSE_LEVEL = 'EDIT_COURSE_LEVEL';
export const TOGGLE_EDIT_COURSE_MODAL = 'TOGGLE_EDIT_COURSE_MODAL';
export const EDIT_COURSE = 'EDIT_COURSE';
export const TOGGLE_DELETE_COURSE_MODAL = 'TOGGLE_DELETE_COURSE_MODAL';
export const DELETE_COURSE = 'DELETE_COURSE';

// enrolments.js
export const FETCH_ENROLMENT = 'FETCH_ENROLMENT';
export const FETCH_ENROLMENTS = 'FETCH_ENROLMENTS';
export const TOGGLE_ADD_ENROLMENT_MODAL = 'TOGGLE_ADD_ENROLMENT_MODAL';
export const ADD_ENROLMENT = 'ADD_ENROLMENT';
export const SET_DATE = 'SET_DATE';
export const SET_TIME = 'SET_TIME';
export const SET_STATUS = 'SET_STATUS';
export const SET_COURSE_ID = 'SET_COURSE_ID';
export const SET_LECTURER_ID = 'SET_LECTURER_ID';
export const EDIT_ENROLMENT_DATE = 'EDIT_ENROLMENT_DATE';
export const EDIT_ENROLMENT_TIME = 'EDIT_ENROLMENT_TIME';
export const EDIT_ENROLMENT_STATUS = 'EDIT_ENROLMENT_STATUS';
export const EDIT_ENROLMENT_COURSE_ID = 'EDIT_ENROLMENT_COURSE_ID';
export const EDIT_ENROLMENT_LECTURER_ID = 'EDIT_ENROLMENT_LECTURER_ID';
export const TOGGLE_EDIT_ENROLMENT_MODAL = 'TOGGLE_EDIT_ENROLMENT_MODAL';
export const EDIT_ENROLMENT = 'EDIT_ENROLMENT';
export const TOGGLE_DELETE_ENROLMENT_MODAL = 'TOGGLE_DELETE_ENROLMENT_MODAL';
export const DELETE_ENROLMENT = 'DELETE_ENROLMENT';

// lecturers.js
export const FETCH_LECTURER = 'FETCH_LECTURER';
export const FETCH_LECTURERS = 'FETCH_LECTURERS';
export const TOGGLE_ADD_LECTURER_MODAL = 'TOGGLE_ADD_LECTURER_MODAL';
export const ADD_LECTURER = 'ADD_LECTURER';
export const SET_LECTURER_NAME = 'SET_LECTURER_NAME';
export const SET_LECTURER_ADDRESS = 'SET_LECTURER_ADDRESS';
export const SET_LECTURER_EMAIL = 'SET_LECTURER_EMAIL';
export const SET_LECTURER_PHONE = 'SET_LECTURER_PHONE';
export const EDIT_LECTURER_NAME = 'EDIT_LECTURER_NAME';
export const EDIT_LECTURER_ADDRESS = 'EDIT_LECTURER_ADDRESS';
export const EDIT_LECTURER_EMAIL = 'EDIT_LECTURER_EMAIL';
export const EDIT_LECTURER_PHONE = 'EDIT_LECTURER_PHONE';
export const TOGGLE_EDIT_LECTURER_MODAL = 'TOGGLE_EDIT_LECTURER_MODAL';
export const EDIT_LECTURER = 'EDIT_LECTURER';
export const TOGGLE_DELETE_LECTURER_MODAL = 'TOGGLE_DELETE_LECTURER_MODAL';
export const DELETE_LECTURER = 'DELETE_LECTURER';

// auth.js
export const SET_NAME = 'SET_NAME';
export const SET_EMAIL = 'SET_EMAIL';
export const SET_PASSWORD = 'SET_PASSWORD';
export const SET_CONFIRM = 'SET_CONFIRM';
export const RESET_LOGIN = 'RESET_LOGIN';
export const RESET_REGISTER = 'RESET_REGISTER';
export const ATTEMPT_LOGIN = 'ATTEMPT_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const SET_TOKEN = 'SET_TOKEN';
export const ATTEMPT_REGISTER = 'ATTEMPT_REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const LOGOUT = 'LOGOUT';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';