// courses.js
export const FETCH_COURSE = 'FETCH_COURSE';
export const FETCH_COURSES = 'FETCH_COURSES';
export const TOGGLE_ADD_COURSE_MODAL = 'TOGGLE_ADD_COURSE_MODAL';
export const ADD_COURSE = 'ADD_COURSE';
export const SET_TITLE = 'SET_TITLE';
export const SET_CODE = 'SET_CODE';
export const SET_DESCRIPTION = 'SET_DESCRIPTION';
export const SET_POINTS = 'SET_POINTS';
export const SET_LEVEL = 'SET_LEVEL';
export const EDIT_COURSE_TITLE = 'EDIT_COURSE_TITLE';
export const EDIT_COURSE_CODE = 'EDIT_COURSE_CODE';
export const EDIT_COURSE_DESCRIPTION = 'EDIT_COURSE_DESCRIPTION';
export const EDIT_COURSE_POINTS = 'EDIT_COURSE_POINTS';
export const EDIT_COURSE_LEVEL = 'EDIT_COURSE_LEVEL';
export const TOGGLE_DELETE_COURSE_MODAL = 'TOGGLE_DELETE_COURSE_MODAL';
export const DELETE_COURSE = 'DELETE_COURSE';
export const TOGGLE_EDIT_COURSE_MODAL = 'TOGGLE_EDIT_COURSE_MODAL';
export const EDIT_COURSE = 'EDIT_COURSE';

// enrolments.js
export const FETCH_ENROLMENT = 'FETCH_ENROLMENT';
export const FETCH_ENROLMENTS = 'FETCH_ENROLMENTS';
export const TOGGLE_ADD_ENROLMENT_MODAL = 'TOGGLE_ADD_ENROLMENT_MODAL';
export const ADD_ENROLMENT = 'ADD_ENROLMENT';
export const SET_DATE = 'SET_DATE';
export const SET_TIME = 'SET_TIME';
export const SET_STATUS = 'SET_STATUS';
export const SET_COURSE_ID = 'SET_COURSE_ID';
export const SET_LECTURER_ID = 'SET_LECTURER_ID';

export const TOGGLE_DELETE_ENROLMENT_MODAL = 'TOGGLE_DELETE_ENROLMENT_MODAL';
export const DELETE_ENROLMENT = 'DELETE_ENROLMENT';

